name: AingZ Tallado READMEs V4
on:
  workflow_dispatch:
    inputs:
      reason:
        description: motivo
        required: true
        default: "tallado-readmes"

permissions:
  contents: write
  pull-requests: write

jobs:
  tallado:
    runs-on: ubuntu-latest
    steps:
      - name: Run PR action
        uses: ./.github/actions/aingz_pr_action
        with:
          reason: ${{ github.event.inputs.reason }}
          branch-prefix: tallado
          commit-message: "AingZ Agent: ${{ github.event.inputs.reason }}"
          pr-body: >
            Tallado automático de READMEs a formato V4 (front-matter + OutputTemplate + crossref desde paths_cache).
          script: |
            python ops/scripts/tallar_readmes.py
