# ---
# file: .github/workflows/aingz_purge_fixes_v2.yml
# code: PURG2
# name: AingZ_Purge_Fixes_V2
# version: v4.0
# date: 2025-08-10
# owner: AingZ_Platform · RwB
# status: active
# xrf:
#   blueprint: RwB_Blueprint_V4
#   mplan: RwB_MasterPlan_V4
#   glossary: CODE_Glossary_v2
#   dictionary: CODE_Triggers_v2
# triggers: [TRG_CONSOLIDATE_TL]
# chg: CHG_main.md#purge_fixes_v2
# chk: CHK_root.md#purge_fixes_v2
# ---

name: "AingZ Purge Fixes V2"

on:
  workflow_dispatch:
    inputs:
      reason:
        description: "Motivo de ejecución (p.ej. purge-fixes)"
        required: false
        default: purge-fixes-v2

permissions:
  actions: write
  contents: write
  pull-requests: write

concurrency:
  group: purge-fixes-v2-${{ github.ref }}
  cancel-in-progress: false

env:
  REASON: ${{ github.event.inputs.reason || 'purge-fixes-v2' }}
  BRANCH_BASENAME: purge/fixes-v2

jobs:
  purge:
    name: "Purge · consolidación y PR"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Preparar estructura de logs
        run: |
          mkdir -p ops/log/purge

      - name: Generar reporte de purge
        id: gen
        shell: bash
        run: |
          stamp=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
          file="ops/log/purge/purge_fixes_v2_${stamp}.md"
          {
            echo "---";
            echo "file: purge_fixes_v2_${stamp}.md";
            echo "code: PURG2";
            echo "name: PurgeFixesV2Report";
            echo "version: v4.0";
            echo "date: ${stamp}";
            echo "owner: AingZ_Platform · RwB";
            echo "status: generated";
            echo "xrf:";
            echo "  blueprint: RwB_Blueprint_V4";
            echo "  mplan: RwB_MasterPlan_V4";
            echo "  glossary: CODE_Glossary_v2";
            echo "  dictionary: CODE_Triggers_v2";
            echo "triggers: [TRG_CONSOLIDATE_TL]";
            echo "chg: CHG_main.md#purge_fixes_v2_${stamp}";
            echo "chk: CHK_root.md#purge_fixes_v2_${stamp}";
            echo "---";
            echo "# Purge Fixes V2";
            echo "- created_at: ${stamp}";
            echo "- reason: ${REASON}";
            echo "- actor: ${GITHUB_ACTOR}";
            echo "\n## Checklist";
            echo "- [ ] Eliminar duplicados y artefactos legacy";
            echo "- [ ] Normalizar rutas V4 y crossrefs";
            echo "- [ ] Actualizar índices y README de bucket";
          } > "$file"
          echo "file=$file" >> "$GITHUB_OUTPUT"

      - name: Crear Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore(purge): Purge Fixes V2 · ${{ env.REASON }}"
          title: "AingZ Purge Fixes V2 · ${{ env.REASON }}"
          body: |
            Origen: workflow `${{ github.workflow }}`.
            Motivo: `${{ env.REASON }}`.
            Archivo generado: `${{ steps.gen.outputs.file }}`.
          branch: ${{ env.BRANCH_BASENAME }}-${{ github.run_id }}
          delete-branch: true
          labels: |
            orchestrated
            purge
            v4

# ---
# OutputTemplate (obligatorio / comentado para GH Actions)
# output_example:
#   status: OK
#   id_asset: purge_fixes_v2
#   generated_by: ai
#   created_at: 2025-08-10T00:00:00-03:00
#   params:
#     - reason: purge-fixes-v2
#   result:
#     - pr_title: "AingZ Purge Fixes V2"
#     - log_file: ops/log/purge/purge_fixes_v2_<stamp>.md
#   log:
#     - step1: generate report
#     - step2: create PR
