name: AingZ Diff Guard
on:
  pull_request:
    paths:
      - "**/*.md"

permissions:
  contents: read

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: No-loss check (markdown only, numstat)
        run: |
          base="${{ github.event.pull_request.base.sha }}"
          head="${{ github.sha }}"

          # Calcular añadidos/quitados SOLO en Markdown
          ns="$(git diff --numstat "$base" "$head" -- ":(glob)**/*.md" || true)"
          echo "numstat:"
          echo "$ns"

          if [ -z "$ns" ]; then
            echo "No markdown changes; skipping no-loss check."
            exit 0
          fi

          added=0
          removed=0
          set +m
          shopt -s lastpipe
          printf '%s\n' "$ns" | while read -r a r path; do
            # los binarios aparecen como '-'
            [[ "$a" =~ ^[0-9]+$ ]] && added=$((added + a))
            [[ "$r" =~ ^[0-9]+$ ]] && removed=$((removed + r))
          done

          echo "added=$added removed=$removed"
          # margen de 10 líneas para evitar falsos positivos
          if [ "$removed" -gt $((added + 10)) ]; then
            echo "Potential loss detected: removed > added + 10"
            exit 1
          fi
          echo "No-loss check passed."
