name: AingZ Incoherence Report
on:
  workflow_dispatch:
    inputs:
      reason:
        description: motivo
        required: true
        default: "incoherences-scan"

permissions:
  contents: write
  pull-requests: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Run PR action
        uses: ./.github/actions/aingz_pr_action
        with:
          reason: ${{ github.event.inputs.reason }}
          branch-prefix: incoherences
          commit-message: "AingZ Agent: incoherences report"
          pr-body: >
            Generación automática de `ops/reports/incoherencias.md` (con severidad) + `ops/reports/incoherencias.json` para chequeo integral V4 (no-loss).
          script: |
            python -m pip install --upgrade pip
            pip install pyyaml
            python ops/scripts/incoherence_report.py
