name: AingZ Diff Guard
on:
  pull_request:
    paths:
      - "**/*.md"

permissions:
  contents: read

jobs:
  diff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: No-loss check
        run: |
          base="${{ github.event.pull_request.base.sha }}"
          head="${{ github.sha }}"
          git diff --unified=0 "$base" "$head" -- "**/*.md" > diff.patch || true
          added=$(grep -E '^\+' diff.patch | grep -v '^\+\+\+' | wc -l || true)
          removed=$(grep -E '^\-' diff.patch | grep -v '^\-\-\-' | wc -l || true)
          echo "added=$added removed=$removed"
          if [ "$removed" -gt "$added" ]; then
            echo "Potential loss detected: removed > added"; exit 1; fi
