name: codex-baseline-check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-codex-baseline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run Codex baseline check
        run: python ops/scripts/run_codex_baseline_v4_check.py
