name: CI Audit V4
on:
  pull_request:
    paths-ignore:
      - "ops/log/**"

permissions:
  contents: read
  pull-requests: write

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pyyaml pytest
      - name: Codex baseline dry-run
        run: |
          if [ -f ops/run_codex_baseline_v4_check.py ]; then
            python ops/run_codex_baseline_v4_check.py
          elif [ -f ops/scripts/run_codex_baseline_v4_check.py ]; then
            python ops/scripts/run_codex_baseline_v4_check.py
          else
            echo "No codex baseline script found, skipping"
          fi
      - name: Unit tests
        run: |
          if [ -d tests ]; then
            pytest -q
          else
            echo "No tests/ dir; skipping"
          fi
