name: validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  kpi-report:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN_RW_B_CI: ${{ secrets.GH_TOKEN_RW_B_CI }}
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN_RW_B_CI }}
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Audit naming
        run: python ops/scripts/audit_naming.py
      - name: Run KPI report
        run: python ops/scripts/report_kpis.py
